#!/bin/sh

RESETWIFI=0
PERSIST=0
PORT=$1
HOST=$2
PID="$$"
RETRY=0
MAXRETRY=10

#TODO: maybe do some kind of logic for daemon/service/tty/pty
#
log() {
	echo $*
	logger monitorGateway $*
}


handleBind() {
	local PORT
	PORT="$1"
	log "enter handleBind"
	EMSG=`cat $LOG | grep "remote port forwarding failed for listen port"`
	if [ -n "$EMSG" ]; then

		log "Error: gateway tunnel failed! $EMSG"
		OFFENDINGPID=`sudo netstat -ltnp  | grep $PORT | awk '{print $7}'`
		if [ -n "$OFFENDINGPID" ]; then
			log "found existing process with port bound, killing process waiting for tcp/ip timeout"
			sudo kill $OFFENDINGPID	
			sleep 242
		fi

	fi


}


connect() {
	local HOST
	local PORT
	HOST="$1"
	PORT="$2"

	log "establishing gateway to $HOST over $PORT"
	#ssh -A -R 0.0.0.0:$PORT:localhost:22 $HOST -E $LOG -N -f 
	ssh -A -R 0.0.0.0:$PORT:localhost:22 $HOST -E $LOG -f "portListening $PORT"
	OUT=`cat $LOG`
	until [ -n "$OUT" ]; do
		OUT=`cat $LOG`
		sleep 1
	done


	log $OUT
	exit

	log $OUT
	sleep 3
	EMSG=`log $OUT | grep "remote port forwarding failed for listen port"`
	#Warning: remote port forwarding failed for listen port 2224
	if [ -n "$EMSG" ]; then
		handleBind "$PORT"

		# re-connect logic
		#
		# avoid re-entrant loop
		#
		log "funcname caller: $FUNCNAME[0]"
		if [ "${FUNCNAME[0]}" != "source" ]; then
			RETRY=`expr $RETRY + 1`
			if [ "$RETRY" -le "$MAXRETRY" ]; then
				log "retry number $RETRY"
				connect "$HOST" "$PORT" 
			else 
				log "bailing after $RETRY retries"
			fi
			
		fi
	fi
}

#  process args
#
if [ -z "$HOST" ]; then
       HOST="grandstreet.group"
fi
#$1 should come from systemd's instance %i
if [ -z "$PORT" ]; then
       PORT=2224
fi
LOG="/tmp/monitorGateway.$PORT.log"

BASENAME=`basename $0`

#should this case happen with pid files from systemd's service management?
#
SHPID=`ps -ef | grep $BASENAME | grep -v $$`
if [ -z "$SHPID" ]; then
	log "bailing, script already running. pid: $SHPID"
	exit;

fi

#   MAIN
#
############

#let systemd
#log "Pid of monitor process $PID"
#log $PID > /tmp/monitorGateway.pid

if [ "$RESETWIFI" -eq "1" ]; then
	nmcli c down wlan0
	nmcli c down wlan1
	nmcli c up wlan0
	nmcli c up wlan1
fi


while [ "$PERSIST"=="1" ]; do
	connect "$HOST" "$PORT"
	sleep 1;
done


connect "$HOST" "$PORT"


#let systemd
#sudo rm /run/monitorGateway.pid
  ISLISTEN=`sudo netstat -lptn | grep $PORT | grep sshd`;
  if [ -n "$ISLISTEN" ]; then
    echo "Tunnel is Active over TCP port $PORT" 
  else
    echo "NO Active Tunnel!!!"
  fi
